Link to Turkish readme page add
RoquesBeach/archipelago pull request #110
Opened 2021-06-09 09:53 UTC by basalumutgazi

Link to Turkish README page on EN, ES, AR README pages was missing. Added it.

2021-07-28 18:53 UTC, johnbampton requested changes

2021-07-28 18:53 UTC, johnbampton commented on lang/ar/README.md
> +[Turkish](lang/tr/README.md)
```suggestion
[Turkish](../tr/README.md)
```

2021-07-28 18:53 UTC, johnbampton commented on lang/es/README.md
> +[Turkish](lang/tr/README.md)
```suggestion
[Turkish](../tr/README.md)
```

2021-08-07 05:02 UTC, jbampton approved these changes

2021-08-07 05:02 UTC, merged